import os

SECRET_KEY = os.environ['SECRET_KEY']
DATABASE_HOST = os.environ['DATABASE_HOST']
DATABASE_USER = os.environ['DATABASE_USER']
DATABASE_PASSWORD = os.environ['DATABASE_PASSWORD']
DATABASE_DB_NAME = os.environ['DATABASE_DB_NAME']
DYNAMODB_NAME = os.environ['DYNAMODB_NAME']
REGION = os.environ['REGION']

